---
# vars file for platform-install
master: "{{hostvars[groups['master'][0]].ansible_default_ipv4.address}}"
worker_nodes: "{% set IP_ARR=[] %}{% for host in groups['nodes'][::] %} {% if IP_ARR.insert(loop.index,hostvars[host].ansible_default_ipv4.address) %}{% endif %} {% endfor %}{{IP_ARR|join(' ')}}"
